@startuml
actor "Użytkownik" as User
actor "Pracownik" as Employee

package "Shelter System" {
    [Shelter] -down-> [Animal] : manages
    [Shelter] -down-> [Employee] : manages
    [Shelter] -down-> [Adoption] : manages
    [Shelter] -down-> [User] : manages

    [Shelter] -right-> [CSV Files] : load and save lists from/to CSV files
    [Shelter] -left-> [Animal] : add, remove,\nand modify animals
    [Shelter] -left-> [Employee] : add, remove,\nand modify employees
    [Shelter] -left-> [Adoption] : add, remove,\nand modify adoptions
    [Shelter] -left-> [User] : add, remove,\nand modify users
}

User -down-> [Adoption] : applies for adoption

Employee -right-> [Animal] : add, modify,\nand view animals
Employee -right-> [Adoption] : adoption management

@enduml