@startuml
actor User
participant Shelter
participant Rejestracja
participant Login
participant Adopcja
participant Oddawanie
participant Wniosek



User -> Shelter : Shelter instance
Shelter -> Rejestracja : onZarejestrujButton()
Rejestracja -> Shelter : onZarejestrujButton()
Shelter -> Login : onZalogujButton()
Login -> Adopcja : onAdopcjaButton()
Login -> Oddawanie : onOddanieButton()
Oddawanie -> Shelter : onDodajButton()
Adopcja -> Wniosek : onAdoptujButton()
Wniosek -> Shelter : onAdoptujButton()
@enduml

